security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                login_path: /
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: server_index
                use_referer: true
            logout:       true
            anonymous:    true
    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/server/, role: ROLE_USER }
